# nl2sql_v3 Configuration

services:
  sparse_vector:
    url: "http://127.0.0.1:8000/api/v1/sparse_vector"
  dense_vector:
    url: "http://127.0.0.1:8000/api/v1/dense_vector"
  translate:
    url: "http://127.0.0.1:8000/api/v1/translate"
  rerank:
    url: "http://127.0.0.1:8000/api/v1/rerank"

  elasticsearch:
    hosts:
      - "http://192.168.116.5:9200"
    index: "tables-metadata"

  llm:
    base_url: "https://openrouter.ai/api/v1"
    api_key: "${OPENROUTER_API_KEY}"
    model: "x-ai/grok-4.1-fast"

recall:
  weights:
    keyword: 0.1
    sparse: 0.6
    dense: 0.3
  # 评估时，返回的最大数量
  top_k: 5
  keyword_threshold: 0.0
  similarity_threshold: 0.7
  rerank_enabled: false
  # 表召回的最终数量
  rerank_top_k: 20
  rerank_threshold: 0.0
  # 粗筛混搜时的最大数量
  hybrid_search_top_k: 100

data:
  metadata: "../data/metadatas.json"
  queries: "../data/query_and_tables.json"

logging:
  level: "INFO"
