# nl2sql_v3 Configuration

services:
  bge_m3:
    url: "http://127.0.0.1:8000/api/v1/bge/encode"
  sparse_vector:
    url: "http://127.0.0.1:8000/api/v1/sparse_vector"
  dense_vector:
    url: "http://127.0.0.1:8000/api/v1/dense_vector"
  translate:
    url: "http://127.0.0.1:8000/api/v1/translate"
  rerank:
    url: "http://127.0.0.1:8000/api/v1/rerank"

  elasticsearch:
    hosts:
      - "http://192.168.116.5:9200"
    index: "nl2sql-tables-metadata"
    dense_dim: 1024

  llm:
    base_url: "https://openrouter.ai/api/v1"
    api_key: "${OPENROUTER_API_KEY}"
    model: "x-ai/grok-4.1-fast"

recall:
  weights:
    keyword: 0.1
    sparse: 0.6
    dense: 0.3
  # rrf 相关配置  
  rrf_enabled: true
  # 召回器的最终返回结果
  top_k: 20
  keyword_threshold: 0.0
  similarity_threshold: 0.7
  # 粗筛混搜时的最大数量
  hybrid_search_top_k: 100
  rerank_enabled: true
  # 精选后的返回结果数
  rerank_top_k: 20
  rerank_threshold: -20

data:
  metadata: "../data/metadatas.json"
  queries: "../data/test_query_and_tables.json"
  use_tables_structured: true
  tables: "../data/test_tables.json"
  tables_structured: "../data/test_tables_structured.json"

logging:
  level: "INFO"
